import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from './_provider/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <head>
        <link rel='apple-touch-icon' href='/icon.png'></link>
        <meta name='theme-color' content='#f69435' />
      </head>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
